name: CI/CD for Frontend

on:
  push:
    branches:
      - main  # Change to your default branch if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # You can specify the version of Node.js

    - name: Install dependencies
      run: npm install  # Run this if you have a package.json

    - name: Build the project
      run: npm run build  # Replace this with your build command if necessary

    - name: Login to Azure
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}  # Set this secret in GitHub

    - name: Deploy to Azure Storage
      run: |
        az storage blob upload-batch \
          --account-name hammadresumestorages  \
          --destination '$web' \
          --source './build'  # Change to your build directory

